import upcomingEvents from './upcoming-events.json';
import {layout,html,card} from './journal-render.mjs';
import {articles,ORIGIN,service} from './journal-store.mjs';
export async function eventsPage(request,env){
 const eventOffer=service('event-coverage');
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
 const upcoming=upcomingEvents.filter(e=>e.endDate>=today);
 const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const guides=(await articles(env.BUCKET)).filter(a=>a.category==='events').slice(0,4);
 const categories=['All','Music','Business','Community','Arts'];
 const group=e=>e.category==='Business'?'Business':e.category==='Community'?'Community':/music/i.test(e.category)?'Music':'Arts';
 const body=`<section class="events-guide" aria-labelledby="events-guide-title"><header class="events-guide-hero"><p class="eyebrow">Florida event guide</p><h1 id="events-guide-title">Find your next <em>night out.</em></h1><p>Concerts, performances, business meetups and creative moments around Florida.</p><a class="events-share" href="https://jamaaltreasures.com/events">jamaaltreasures.com/events ↗</a><div class="event-filters" aria-label="Filter events">${categories.map(c=>`<button type="button" data-event-filter="${c}" aria-pressed="${c==='All'}">${c}</button>`).join('')}</div></header><div id="upcoming-events" class="upcoming-grid">${upcoming.map(e=>`<article class="upcoming-card" data-event-category="${group(e)}"><a class="upcoming-art" href="${escape(e.flyerUrl||e.url)}" target="_blank" rel="noopener noreferrer" aria-label="${escape(e.title)} flyer"><img src="${escape(e.image)}" alt="${escape(e.title)} event artwork" loading="lazy" decoding="async" referrerpolicy="no-referrer"></a><div class="upcoming-info"><p class="upcoming-date"><time datetime="${e.startDate}">${escape(e.dateLabel)}</time>${e.time?' · '+escape(e.time):''}</p><h2>${escape(e.title)}</h2><p class="upcoming-place">${escape(e.venue)}<br>${escape(e.city)}, Florida</p><p class="upcoming-kind">${escape(e.category)}</p><div class="event-card-actions"><a class="event-details" href="${escape(e.url)}" target="_blank" rel="noopener noreferrer">Event details ↗</a><a class="event-flyer-link" href="${escape(e.flyerUrl||e.image)}" target="_blank" rel="noopener noreferrer">View flyer ↗</a></div></div></article>`).join('')}</div>${upcoming.length?'':'<p>More dates are on the way.</p>'}</section>
 <header class="journal-heading events-heading"><p class="eyebrow">Events & Media</p><h2>Cinematic coverage.<br><em>The story behind it.</em></h2><p>Capture the energy, the people and the details worth sharing.</p><div class="events-actions"><a class="button glass" href="/contact?project=Event%20Coverage%20%28%24450%29">Book event filming ↗</a><a class="button glass" href="#editorial-invite">Invite Journal coverage ↓</a></div></header>
 <figure class="events-cover"><img src="/assets/editorial/event-crowd-nicholas-green.webp" width="1200" height="800" alt="Fans cheering together at a live concert" decoding="async"><figcaption>Representative event image · Photo by <a href="https://unsplash.com/photos/excited-crowd-cheering-at-concert-or-event-nPz8akkUmDI" target="_blank" rel="noopener noreferrer">Nicholas Green / Unsplash</a>.</figcaption></figure>
 <div class="events-paths"><section class="glass glass-panel events-panel" data-refract data-optics-edge data-optics-source="atmosphere"><p class="eyebrow">For your event or brand</p><h2>Book the visuals.</h2><p class="events-price">$450 <span>Event Coverage</span></p><p>Capture the energy, the people and the details worth sharing.</p><ul><li>Up to 2 hours of event filming in Florida</li><li>One edited 60 to 90 second highlight video</li><li>3 vertical social clips and 2 revision rounds</li><li>${eventOffer.time}</li></ul><p class="events-fine">Longer coverage and travel outside the agreed area are quoted before booking. Photography or a commissioned article can be discussed separately. They are not included in this video package.</p><a class="text-action" href="/prices?category=production">See the current package <span aria-hidden="true">↗</span></a></section>
 <section class="glass glass-panel events-panel" data-refract data-optics-edge data-optics-source="atmosphere"><p class="eyebrow">For a story worth telling</p><h2>Bring us the story.</h2><p>New voices. Small stages. Creative communities with something to say. The Journal is developing original event stories, artist conversations and visual reporting.</p><p>Send the official event details, a possible story angle and the right person to contact. Invitations are considered for relevance, access and availability.</p><ul><li>Verified previews that help people plan</li><li>Original interviews and artist profiles</li><li>Reported stories with credited visuals</li></ul><p class="events-fine">Editorial access is decided by the organizer. An invitation does not guarantee attendance, publication or favorable coverage. Paid or hosted coverage is disclosed.</p><a class="text-action" href="#editorial-invite">Share an editorial invitation <span aria-hidden="true">↓</span></a></section></div>
 <section class="events-proof"><div><p class="eyebrow">The person making it</p><h2>Meet Jamaal.</h2><p>Jamaal Treasures, also known as CJ, is a freelance creative director, filmmaker and musician. His directed music videos have earned more than 5 million combined YouTube views.</p><p>That is music video reach, separate from the readership of this new Journal. Explore his directing work and real client feedback while the event reporting archive grows.</p><div class="events-inline-links"><a href="/work">Watch the music videos ↗</a><a href="/reviews">Read client reviews ↗</a><a href="/bio">Read the biography ↗</a></div></div><img src="/assets/jamaal-portrait-480.webp" width="480" height="721" alt="Jamaal Treasures, freelance creative director and musician" loading="lazy"></section>
 <section class="journal-related events-reading"><p class="eyebrow">From the Journal</p><h2>Plan a better event story.</h2><p class="events-reading-note">Start with the planning guide below. Original event reports will appear here as they are published, with real event details, reporting credits and sources.</p><div class="journal-grid">${guides.map(a=>card(a)).join('')}</div><a class="text-action" href="/blog?category=events">Browse Florida event stories and guides ↗</a></section>
 <section id="editorial-invite" class="events-invite glass glass-panel"><div><p class="eyebrow">Editorial invitations</p><h2>What’s happening?</h2><p>Share the official event link and the story you think deserves a closer look. This is an invitation to consider editorial coverage, not a paid production booking.</p><p>For booked filming, <a href="/contact?project=Event%20Coverage%20%28%24450%29">use the event coverage inquiry</a>.</p></div><form action="https://formsubmit.co/jamaaltreasures@gmail.com" method="post"><input type="hidden" name="_subject" value="Editorial event invitation | Jamaal Treasures Journal"><input type="text" name="_honey" class="honeypot" tabindex="-1" autocomplete="off" aria-hidden="true"><div class="events-form-grid"><label>Your name<input name="name" autocomplete="name" required maxlength="100"></label><label>Email<input name="email" type="email" autocomplete="email" required maxlength="254"></label><label>Event name<input name="event_name" required maxlength="180"></label><label>Event date<input name="event_date" type="date" required></label><label>Venue and city<input name="venue_city" required maxlength="200"></label><label>Official event link<input name="official_event_url" type="url" placeholder="https://" required maxlength="600"></label><label>Organizer or media contact<input name="organizer_contact" maxlength="250"></label><label>Credential deadline, if known<input name="credential_deadline" type="date"></label><label class="events-full">What’s the story?<textarea name="story_angle" rows="4" required maxlength="2000" placeholder="The artist, moment or idea people should know about"></textarea></label></div><p class="form-privacy">Sent through FormSubmit to Jamaal. <a href="/privacy">Privacy</a>.</p><button class="button glass" type="submit" data-refract data-optics-edge>Send an invitation <span aria-hidden="true">↗</span></button></form></section>
 <section class="events-editorial"><div><h2>Clear credits. Real context.</h2><p>The Journal is new. Current guides and sourced news are distinct from future on site reporting. Every event story should identify its author, publication date, actual event date, location and sources. Original and supplied visuals are credited. Generated imagery is never presented as documentary evidence.</p><p>AI assistance is disclosed. Paid assignments and hosted access are identified. Corrections can be sent to the business email with the article link and supporting information.</p></div><address><strong>Jamaal Treasures</strong><a href="tel:+19412949274">941-294-9274</a><a href="mailto:jamaaltreasures@gmail.com">jamaaltreasures@gmail.com</a><a href="https://www.instagram.com/jamaaltreasures/" target="_blank" rel="noopener noreferrer">@jamaaltreasures</a><a href="/contact">Service areas and booking</a></address></section>`;
 const schema={'@context':'https://schema.org','@graph':[{'@type':'Person','@id':ORIGIN+'/#jamaal',name:'Jamaal Treasures',url:ORIGIN+'/bio',telephone:'+19412949274',sameAs:['https://www.instagram.com/jamaaltreasures/','https://www.youtube.com/@cimtexpro5593']},{'@type':'WebPage','@id':ORIGIN+'/events#webpage',url:ORIGIN+'/events',name:'Events & Media | Jamaal Treasures',about:{'@id':ORIGIN+'/#jamaal'},isPartOf:{'@id':ORIGIN+'/#website'}},{'@type':'Service',name:'Event Coverage',provider:{'@id':ORIGIN+'/#jamaal'},url:ORIGIN+'/prices?category=production',areaServed:{'@type':'State',name:'Florida'},offers:{'@type':'Offer',price:String(eventOffer.price),priceCurrency:'USD',url:ORIGIN+'/contact?project=Event%20Coverage%20%28%24450%29'}}]};
 return html(layout('Events & Media','Explore upcoming Florida concerts, performances and creative events. Find dates, venues and official event links, or book event filming with Jamaal Treasures.','/events',body,[schema]));
}
