// Phase 3 liquid glass filter defs. Generated by
// ~/workspace/site-revamp/generate-marble-glass.py; do not hand edit.
// Authored displacement maps: neutral gray center, red and green rim
// gradients. Same block is injected into the root HTML pages.
// Each chain finishes with saturate and brightness primitives inside
// the filter itself, because Chromium drops CSS functions written
// after a url reference in a backdrop filter value.
export const glassDefs=`<svg class="lg-defs" width="0" height="0" aria-hidden="true" focusable="false" style="position:absolute;overflow:hidden">
<defs>
<filter id="lg-card" filterUnits="objectBoundingBox" primitiveUnits="objectBoundingBox" x="-2%" y="-2%" width="104%" height="104%" color-interpolation-filters="sRGB">
<feImage href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScyMDAnIGhlaWdodD0nMjAwJyB2aWV3Qm94PScwIDAgMjAwIDIwMCc+CjxyZWN0IHdpZHRoPScyMDAnIGhlaWdodD0nMjAwJyBmaWxsPScjODA4MDgwJy8+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9J2wnIHgxPScwJyB5MT0nMCcgeDI9JzEnIHkyPScwJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyNmZjgwODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9J3InIHgxPScwJyB5MT0nMCcgeDI9JzEnIHkyPScwJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyMwMDgwODAnLz48L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9J3QnIHgxPScwJyB5MT0nMCcgeDI9JzAnIHkyPScxJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyM4MGZmODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9J2InIHgxPScwJyB5MT0nMCcgeDI9JzAnIHkyPScxJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyM4MDgwMDAnLz48L2xpbmVhckdyYWRpZW50Pgo8L2RlZnM+CjxyZWN0IHg9JzAnIHk9JzAnIHdpZHRoPSczOCcgaGVpZ2h0PScyMDAnIGZpbGw9J3VybCgjbCknLz4KPHJlY3QgeD0nMTYyJyB5PScwJyB3aWR0aD0nMzgnIGhlaWdodD0nMjAwJyBmaWxsPSd1cmwoI3IpJy8+CjxyZWN0IHg9JzAnIHk9JzAnIHdpZHRoPScyMDAnIGhlaWdodD0nMzgnIGZpbGw9J3VybCgjdCknLz4KPHJlY3QgeD0nMCcgeT0nMTYyJyB3aWR0aD0nMjAwJyBoZWlnaHQ9JzM4JyBmaWxsPSd1cmwoI2IpJy8+Cjwvc3ZnPg==" preserveAspectRatio="none" x="0" y="0" width="1" height="1" result="map"/>
<feGaussianBlur in="SourceGraphic" stdDeviation="0.0028" result="soft"/>
<feDisplacementMap in="soft" in2="map" scale="0.085" xChannelSelector="R" yChannelSelector="G" result="disp"/>
<feColorMatrix in="disp" type="saturate" values="1.03" result="sat"/>
<feComponentTransfer in="sat"><feFuncR type="linear" slope="1.01"/><feFuncG type="linear" slope="1.01"/><feFuncB type="linear" slope="1.01"/></feComponentTransfer>
</filter>
<filter id="lg-chip" filterUnits="objectBoundingBox" primitiveUnits="objectBoundingBox" x="-2%" y="-2%" width="104%" height="104%" color-interpolation-filters="sRGB">
<feImage href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPScxNjAnIGhlaWdodD0nODAnIHZpZXdCb3g9JzAgMCAxNjAgODAnPgo8cmVjdCB3aWR0aD0nMTYwJyBoZWlnaHQ9JzgwJyBmaWxsPScjODA4MDgwJy8+CjxkZWZzPgo8bGluZWFyR3JhZGllbnQgaWQ9J2wnIHgxPScwJyB5MT0nMCcgeDI9JzEnIHkyPScwJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyNmZjgwODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9J3InIHgxPScwJyB5MT0nMCcgeDI9JzEnIHkyPScwJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyMwMDgwODAnLz48L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9J3QnIHgxPScwJyB5MT0nMCcgeDI9JzAnIHkyPScxJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyM4MGZmODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48L2xpbmVhckdyYWRpZW50Pgo8bGluZWFyR3JhZGllbnQgaWQ9J2InIHgxPScwJyB5MT0nMCcgeDI9JzAnIHkyPScxJz48c3RvcCBvZmZzZXQ9JzAnIHN0b3AtY29sb3I9JyM4MDgwODAnLz48c3RvcCBvZmZzZXQ9JzEnIHN0b3AtY29sb3I9JyM4MDgwMDAnLz48L2xpbmVhckdyYWRpZW50Pgo8L2RlZnM+CjxyZWN0IHg9JzAnIHk9JzAnIHdpZHRoPSc0NicgaGVpZ2h0PSc4MCcgZmlsbD0ndXJsKCNsKScvPgo8cmVjdCB4PScxMTQnIHk9JzAnIHdpZHRoPSc0NicgaGVpZ2h0PSc4MCcgZmlsbD0ndXJsKCNyKScvPgo8cmVjdCB4PScwJyB5PScwJyB3aWR0aD0nMTYwJyBoZWlnaHQ9JzI2JyBmaWxsPSd1cmwoI3QpJy8+CjxyZWN0IHg9JzAnIHk9JzU0JyB3aWR0aD0nMTYwJyBoZWlnaHQ9JzI2JyBmaWxsPSd1cmwoI2IpJy8+Cjwvc3ZnPg==" preserveAspectRatio="none" x="0" y="0" width="1" height="1" result="map"/>
<feGaussianBlur in="SourceGraphic" stdDeviation="0.012" result="soft"/>
<feDisplacementMap in="soft" in2="map" scale="0.16" xChannelSelector="R" yChannelSelector="G" result="disp"/>
<feColorMatrix in="disp" type="saturate" values="1.03" result="sat"/>
<feComponentTransfer in="sat"><feFuncR type="linear" slope="1.01"/><feFuncG type="linear" slope="1.01"/><feFuncB type="linear" slope="1.01"/></feComponentTransfer>
</filter>
</defs>
</svg>`;
