import catalog from '../offers.json' with {type:'json'};
import {schemaTag} from './search-schema.mjs';
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const copy=value=>esc(String(value??'').replace(/[-–—]/g,' '));
export const servicePaths=['ai-music-reels','event-coverage'];
export function servicePage(request){
 const path=new URL(request.url).pathname.replace(/\/+$/,'').slice(1);
 if(!servicePaths.includes(path))return null;
 if(!['GET','HEAD'].includes(request.method))return new Response('Method not allowed',{status:405,headers:{Allow:'GET, HEAD'}});
 const offer=catalog.services.find(item=>item.id===path),url=`https://jamaaltreasures.com/${path}`;
 const label=path==='ai-music-reels'?'Buy AI Reel, $80':'Buy Event Package, $450';
 const schema={'@context':'https://schema.org','@type':'Service',name:offer.name,description:offer.summary,url,provider:{'@type':'Organization',name:'Jamaal Treasures',url:'https://jamaaltreasures.com/'},areaServed:'Florida',offers:{'@type':'Offer',price:offer.price,priceCurrency:'USD',url:offer.checkoutUrl}};
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${copy(offer.name)} | Jamaal Treasures</title><meta name="description" content="${copy(offer.summary)}"><link rel="canonical" href="${url}"><link rel="icon" href="/assets/jamaal-key.svg">${schemaTag(schema)}<style>*{box-sizing:border-box}body{margin:0;background:#FAF7F2 url(/assets/marble.svg) center top/1100px repeat;color:#111114;font:17px/1.65 system-ui,sans-serif}a{color:#111114}header,main,footer{max-width:760px;margin:auto;padding:24px}header{display:flex;flex-wrap:wrap;justify-content:space-between;gap:20px;border-bottom:1px solid rgba(17,17,20,.12)}nav{display:flex;gap:22px}h1{font-size:clamp(32px,7vw,52px);line-height:1.1}h2{font-size:24px}li{margin:12px 0}.price{font-size:36px;font-weight:800}.buy{display:inline-flex;align-items:center;justify-content:center;min-height:54px;padding:14px 24px;border-radius:14px;background:#A7192F;color:white;font-weight:800;text-decoration:none}.details{border:1px solid rgba(17,17,20,.12);border-radius:20px;padding:24px;margin:28px 0;background:#ffffff}.muted{color:#6E6A63}a:focus-visible{outline:3px solid #A7192F;outline-offset:5px}footer{border-top:1px solid rgba(17,17,20,.12)}.foot-nav{display:flex;flex-wrap:wrap;gap:8px 18px;margin-top:14px}</style></head><body><header><a href="/">Jamaal Treasures</a><nav aria-label="Main navigation"><a href="/prices">Prices</a><a href="/events">Events</a><a href="/contact">Book a project</a></nav></header><main><h1>${copy(offer.name)}</h1><p>${copy(offer.summary)}</p><p class="price">$${offer.price} <small>USD</small></p><a class="buy" href="${esc(offer.checkoutUrl)}">${label}</a><section class="details"><h2>What you get</h2><ul>${offer.deliverables.map(item=>`<li>${copy(item)}</li>`).join('')}</ul><h2>Timing</h2><p>${copy(offer.time)}</p>${offer.note?`<p>${copy(offer.note)}</p>`:''}</section><h2>Let’s plan your project</h2><p>${copy(offer.idealFor)}</p><p><a href="/contact?project=${path}">Send your brief or ask about availability</a></p><p class="muted">Square shows the final total at checkout.</p></main><footer><a href="mailto:jamaaltreasures@gmail.com">jamaaltreasures@gmail.com</a><p><a href="tel:+19412949274">941 294 9274</a></p><nav class="foot-nav" aria-label="Explore"><a href="/">Home</a><a href="/events">Events</a><a href="/prices">Prices</a><a href="/blog">Blog</a><a href="/contact">Book a project</a></nav></footer></body></html>`;
 return new Response(request.method==='HEAD'?null:html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=60'}});
}
